title: Alexander Messejnikov
description: "&#8226; (204) 510-9816<br>&#8226; messejnikovalexander@gmail.com<br>&#8226; Winnipeg, MB<br>&#8226; <a href=\"https://www.linkedin.com/in/alex-messejnikov\">LinkedIn</a>"

theme: jekyll-theme-minimal

---
<p align="center">
  <small><a href="https://github.com/your-username/your-repo-name">View Source Files on GitHub</a></small>
</p>
